"""add colonne user_id

Revision ID: 0725865adf1a
Revises: bf81623a1139
Create Date: 2025-09-10 20:24:15.517258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0725865adf1a'
down_revision: Union[str, Sequence[str], None] = 'bf81623a1139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'predictions', 'users', ['user_id'], ['id'], ondelete='Cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.drop_column('predictions', 'user_id')
    # ### end Alembic commands ###
